{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOOLAST8ANI9ZjSvyn1qS66",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/dakshatham28/AI-Lab/blob/main/1WA24CS102_WEEK1_VACUUMCLEANER_TICTACTOE_.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "print(\"Name: DAKSHATHA M\")\n",
        "print(\"USN: 1WA24CS102\")\n",
        "print()\n",
        "\n",
        "# Agent function table\n",
        "agent_table = {\n",
        "    ('Clean', 'A'): 'MoveRight',\n",
        "    ('Clean', 'B'): 'MoveLeft',\n",
        "    ('Dirty', 'A'): 'Suck',\n",
        "    ('Dirty', 'B'): 'Suck',\n",
        "}\n",
        "\n",
        "# Vacuum cleaner class\n",
        "class VacuumCleaner:\n",
        "    def __init__(self, location='A', status='Clean'):\n",
        "        self.location = location\n",
        "        self.status = status\n",
        "\n",
        "    def percept(self):\n",
        "        return self.status\n",
        "\n",
        "    def act(self, action):\n",
        "        if action == 'MoveRight':\n",
        "            self.location = 'B'\n",
        "        elif action == 'MoveLeft':\n",
        "            self.location = 'A'\n",
        "        elif action == 'Suck':\n",
        "            self.status = 'Clean'\n",
        "\n",
        "# Table-driven agent function\n",
        "def table_driven_agent(percept):\n",
        "    return agent_table.get(percept, 'NoOp')\n",
        "\n",
        "# Main simulation loop\n",
        "if __name__ == \"__main__\":\n",
        "    vacuum = VacuumCleaner(location='A', status='Dirty')\n",
        "\n",
        "    for step in range(1, 6):  # Run for 5 time steps\n",
        "        current_percept = vacuum.percept()\n",
        "        action = table_driven_agent((current_percept, vacuum.location))\n",
        "        print(f\"Step {step} | Percept: {current_percept}, Action: {action}\")\n",
        "\n",
        "        if action != 'NoOp':\n",
        "            vacuum.act(action)\n",
        "\n",
        "        print(f\"Location: {vacuum.location}, Status: {vacuum.status}\\n\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "fYhWvHAUMxGC",
        "outputId": "cbdd7462-e9fb-4973-a37e-b151810fee03"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Name: DAKSHATHA M\n",
            "USN: 1WA24CS102\n",
            "\n",
            "Step 1 | Percept: Dirty, Action: Suck\n",
            "Location: A, Status: Clean\n",
            "\n",
            "Step 2 | Percept: Clean, Action: MoveRight\n",
            "Location: B, Status: Clean\n",
            "\n",
            "Step 3 | Percept: Clean, Action: MoveLeft\n",
            "Location: A, Status: Clean\n",
            "\n",
            "Step 4 | Percept: Clean, Action: MoveRight\n",
            "Location: B, Status: Clean\n",
            "\n",
            "Step 5 | Percept: Clean, Action: MoveLeft\n",
            "Location: A, Status: Clean\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "print(\"Name: DAKSHATHA M\")\n",
        "print(\"USN: 1WA24CS102\")\n",
        "print()\n",
        "\n",
        "import math\n",
        "\n",
        "# Path cost\n",
        "path_cost = 0\n",
        "\n",
        "# Initialize the board with the given stage from the image\n",
        "board = [\"O\", \" \", \"X\",\n",
        "         \"X\", \" \", \" \",\n",
        "         \"X\", \"O\", \"O\"]\n",
        "\n",
        "\n",
        "def print_board(b):\n",
        "    print(f\"\\n {b[0]} | {b[1]} | {b[2]} \")\n",
        "    print(\"---|---|---\")\n",
        "    print(f\" {b[3]} | {b[4]} | {b[5]} \")\n",
        "    print(\"---|---|---\")\n",
        "    print(f\" {b[6]} | {b[7]} | {b[8]} \\n\")\n",
        "\n",
        "\n",
        "def is_winner(b, letter):\n",
        "    # Check rows, columns, and diagonals\n",
        "    winning_conditions = [\n",
        "        (0, 1, 2), (3, 4, 5), (6, 7, 8),  # Rows\n",
        "        (0, 3, 6), (1, 4, 7), (2, 5, 8),  # Columns\n",
        "        (0, 4, 8), (2, 4, 6)               # Diagonals\n",
        "    ]\n",
        "\n",
        "    return any(\n",
        "        b[i] == b[j] == b[k] == letter\n",
        "        for i, j, k in winning_conditions\n",
        "    )\n",
        "\n",
        "\n",
        "def is_board_full(b):\n",
        "    return \" \" not in b\n",
        "\n",
        "\n",
        "def get_empty_cells(b):\n",
        "    return [i for i, spot in enumerate(b) if spot == \" \"]\n",
        "\n",
        "\n",
        "# Minimax algorithm for unbeatable AI\n",
        "def minimax(b, is_maximizing):\n",
        "\n",
        "    if is_winner(b, \"O\"):\n",
        "        return 1\n",
        "\n",
        "    if is_winner(b, \"X\"):\n",
        "        return -1\n",
        "\n",
        "    if is_board_full(b):\n",
        "        return 0\n",
        "\n",
        "    if is_maximizing:\n",
        "        best_score = -math.inf\n",
        "\n",
        "        for cell in get_empty_cells(b):\n",
        "            b[cell] = \"O\"\n",
        "\n",
        "            score = minimax(b, False)\n",
        "\n",
        "            b[cell] = \" \"\n",
        "\n",
        "            best_score = max(score, best_score)\n",
        "\n",
        "        return best_score\n",
        "\n",
        "    else:\n",
        "        best_score = math.inf\n",
        "\n",
        "        for cell in get_empty_cells(b):\n",
        "            b[cell] = \"X\"\n",
        "\n",
        "            score = minimax(b, True)\n",
        "\n",
        "            b[cell] = \" \"\n",
        "\n",
        "            best_score = min(score, best_score)\n",
        "\n",
        "        return best_score\n",
        "\n",
        "\n",
        "def ai_move(b):\n",
        "    global path_cost\n",
        "\n",
        "    best_score = -math.inf\n",
        "    move = None\n",
        "\n",
        "    for cell in get_empty_cells(b):\n",
        "        b[cell] = \"O\"\n",
        "\n",
        "        score = minimax(b, False)\n",
        "\n",
        "        b[cell] = \" \"\n",
        "\n",
        "        if score > best_score:\n",
        "            best_score = score\n",
        "            move = cell\n",
        "\n",
        "    if move is not None:\n",
        "        b[move] = \"O\"\n",
        "\n",
        "        # Increase path cost for AI move\n",
        "        path_cost += 1\n",
        "\n",
        "\n",
        "def player_move(b):\n",
        "    global path_cost\n",
        "\n",
        "    while True:\n",
        "        try:\n",
        "            choice = int(input(\"Choose a position (0-8): \"))\n",
        "\n",
        "            if b[choice] == \" \":\n",
        "                b[choice] = \"X\"\n",
        "\n",
        "                # Increase path cost for player's move\n",
        "                path_cost += 1\n",
        "\n",
        "                break\n",
        "\n",
        "            else:\n",
        "                print(\"That spot is taken! Try again.\")\n",
        "\n",
        "        except (ValueError, IndexError):\n",
        "            print(\"Invalid input. Enter a number between 0 and 8.\")\n",
        "\n",
        "\n",
        "# Main Game Loop\n",
        "print(\"Welcome to Tic-Tac-Toe!\")\n",
        "print(\"You are X and the AI is O.\")\n",
        "print_board(board)\n",
        "\n",
        "while True:\n",
        "\n",
        "    # Player's turn\n",
        "    player_move(board)\n",
        "    print_board(board)\n",
        "\n",
        "    # Check if player wins\n",
        "    if is_winner(board, \"X\"):\n",
        "        print(\"You win!\")\n",
        "        print(\"Path Cost:\", path_cost)\n",
        "        break\n",
        "\n",
        "    # Check for draw\n",
        "    if is_board_full(board):\n",
        "        print(\"It's a tie!\")\n",
        "        print(\"Path Cost:\", path_cost)\n",
        "        break\n",
        "\n",
        "    # AI's turn\n",
        "    print(\"AI's turn...\")\n",
        "    ai_move(board)\n",
        "    print_board(board)\n",
        "\n",
        "    # Check if AI wins\n",
        "    if is_winner(board, \"O\"):\n",
        "        print(\"AI wins!\")\n",
        "        print(\"Path Cost:\", path_cost)\n",
        "        break\n",
        "\n",
        "    # Check for draw\n",
        "    if is_board_full(board):\n",
        "        print(\"It's a tie!\")\n",
        "        print(\"Path Cost:\", path_cost)\n",
        "        break"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "TWYrpTQuOMuz",
        "outputId": "43967ce8-1880-48a3-8456-ff4c760eb39d"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Name: DAKSHATHA M\n",
            "USN: 1WA24CS102\n",
            "\n",
            "Welcome to Tic-Tac-Toe!\n",
            "You are X and the AI is O.\n",
            "\n",
            " O |   | X \n",
            "---|---|---\n",
            " X |   |   \n",
            "---|---|---\n",
            " X | O | O \n",
            "\n",
            "Choose a position (0-8): 4\n",
            "\n",
            " O |   | X \n",
            "---|---|---\n",
            " X | X |   \n",
            "---|---|---\n",
            " X | O | O \n",
            "\n",
            "You win!\n",
            "Path Cost: 1\n"
          ]
        }
      ]
    }
  ]
}