# -*- coding: utf-8 -*-
"""1WA24CS102_WEEK1_VACUUMCLEANER_TICTACTOE_.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HnxpP9LUNUpemW4N5egt5IDiYI-KFV_E
"""

print("Name: DAKSHATHA M")
print("USN: 1WA24CS102")
print()

# Agent function table
agent_table = {
    ('Clean', 'A'): 'MoveRight',
    ('Clean', 'B'): 'MoveLeft',
    ('Dirty', 'A'): 'Suck',
    ('Dirty', 'B'): 'Suck',
}

# Vacuum cleaner class
class VacuumCleaner:
    def __init__(self, location='A', status='Clean'):
        self.location = location
        self.status = status

    def percept(self):
        return self.status

    def act(self, action):
        if action == 'MoveRight':
            self.location = 'B'
        elif action == 'MoveLeft':
            self.location = 'A'
        elif action == 'Suck':
            self.status = 'Clean'

# Table-driven agent function
def table_driven_agent(percept):
    return agent_table.get(percept, 'NoOp')

# Main simulation loop
if __name__ == "__main__":
    vacuum = VacuumCleaner(location='A', status='Dirty')

    for step in range(1, 6):  # Run for 5 time steps
        current_percept = vacuum.percept()
        action = table_driven_agent((current_percept, vacuum.location))
        print(f"Step {step} | Percept: {current_percept}, Action: {action}")

        if action != 'NoOp':
            vacuum.act(action)

        print(f"Location: {vacuum.location}, Status: {vacuum.status}\n")

print("Name: DAKSHATHA M")
print("USN: 1WA24CS102")
print()

import math

# Path cost
path_cost = 0

# Initialize the board with the given stage from the image
board = ["O", " ", "X",
         "X", " ", " ",
         "X", "O", "O"]


def print_board(b):
    print(f"\n {b[0]} | {b[1]} | {b[2]} ")
    print("---|---|---")
    print(f" {b[3]} | {b[4]} | {b[5]} ")
    print("---|---|---")
    print(f" {b[6]} | {b[7]} | {b[8]} \n")


def is_winner(b, letter):
    # Check rows, columns, and diagonals
    winning_conditions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),  # Rows
        (0, 3, 6), (1, 4, 7), (2, 5, 8),  # Columns
        (0, 4, 8), (2, 4, 6)               # Diagonals
    ]

    return any(
        b[i] == b[j] == b[k] == letter
        for i, j, k in winning_conditions
    )


def is_board_full(b):
    return " " not in b


def get_empty_cells(b):
    return [i for i, spot in enumerate(b) if spot == " "]


# Minimax algorithm for unbeatable AI
def minimax(b, is_maximizing):

    if is_winner(b, "O"):
        return 1

    if is_winner(b, "X"):
        return -1

    if is_board_full(b):
        return 0

    if is_maximizing:
        best_score = -math.inf

        for cell in get_empty_cells(b):
            b[cell] = "O"

            score = minimax(b, False)

            b[cell] = " "

            best_score = max(score, best_score)

        return best_score

    else:
        best_score = math.inf

        for cell in get_empty_cells(b):
            b[cell] = "X"

            score = minimax(b, True)

            b[cell] = " "

            best_score = min(score, best_score)

        return best_score


def ai_move(b):
    global path_cost

    best_score = -math.inf
    move = None

    for cell in get_empty_cells(b):
        b[cell] = "O"

        score = minimax(b, False)

        b[cell] = " "

        if score > best_score:
            best_score = score
            move = cell

    if move is not None:
        b[move] = "O"

        # Increase path cost for AI move
        path_cost += 1


def player_move(b):
    global path_cost

    while True:
        try:
            choice = int(input("Choose a position (0-8): "))

            if b[choice] == " ":
                b[choice] = "X"

                # Increase path cost for player's move
                path_cost += 1

                break

            else:
                print("That spot is taken! Try again.")

        except (ValueError, IndexError):
            print("Invalid input. Enter a number between 0 and 8.")


# Main Game Loop
print("Welcome to Tic-Tac-Toe!")
print("You are X and the AI is O.")
print_board(board)

while True:

    # Player's turn
    player_move(board)
    print_board(board)

    # Check if player wins
    if is_winner(board, "X"):
        print("You win!")
        print("Path Cost:", path_cost)
        break

    # Check for draw
    if is_board_full(board):
        print("It's a tie!")
        print("Path Cost:", path_cost)
        break

    # AI's turn
    print("AI's turn...")
    ai_move(board)
    print_board(board)

    # Check if AI wins
    if is_winner(board, "O"):
        print("AI wins!")
        print("Path Cost:", path_cost)
        break

    # Check for draw
    if is_board_full(board):
        print("It's a tie!")
        print("Path Cost:", path_cost)
        break